config/routes.rb
Rails.application.routes.draw do
  #
  # Manager
  #

  get 'manager/sign_in' => 'administrations/sessions#new'
  delete 'manager/sign_out' => 'administrations/sessions#destroy'
  namespace :manager do
    resources :procedures, only: [:index, :show] do
      post 'whitelist', on: :member
      post 'draft', on: :member
      post 'discard', on: :member
      post 'restore', on: :member
      post 'add_administrateur', on: :member
      post 'change_piece_justificative_template', on: :member
      get 'export_mail_brouillons', on: :member
    end

    resources :dossiers, only: [:index, :show] do
      post 'discard', on: :member
      post 'restore', on: :member
      post 'repasser_en_instruction', on: :member
    end

    resources :administrateurs, only: [:index, :show, :new, :create] do
      post 'reinvite', on: :member
      delete 'delete', on: :member
    end

    resources :users, only: [:index, :show, :edit, :update] do
      delete 'delete', on: :member
      post 'resend_confirmation_instructions', on: :member
      put 'enable_feature', on: :member
    end

    resources :instructeurs, only: [:index, :show] do
      post 'reinvite', on: :member
      delete 'delete', on: :member
    end

    resources :dossiers, only: [:show]

    resources :demandes, only: [:index]

    resources :bill_signatures, only: [:index]

    resources :services, only: [:index, :show]

    post 'demandes/create_administrateur'
    post 'demandes/refuse_administrateur'

    authenticate :administration do
      mount Flipper::UI.app(-> { Flipper.instance }) => "/features", as: :flipper
      match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]
    end

    root to: "administrateurs#index"
  end

  #
  # Letter Opener
  #

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  #
  # Monitoring
  #

  get "/ping" => "ping#index"

  #
  # Authentication
  #

  devise_for :administrations,
    skip: [:password, :registrations, :sessions],
    controllers: {
      omniauth_callbacks: 'administrations/omniauth_callbacks'
    }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/users/no_procedure' => 'users/sessions#no_procedure'
    get 'connexion-par-jeton/:id' => 'users/sessions#sign_in_by_link', as: 'sign_in_by_link'
    get 'lien-envoye/:email' => 'users/sessions#link_sent', constraints: { email: /.*/ }, as: 'link_sent'
  end

  devise_scope :administrateur do
    get '/administrateurs/password/test_strength' => 'administrateurs/passwords#test_strength'
  end

  #
  # Main routes
  #

  root 'root#index'
  get '/administration' => 'root#administration'

  get 'users' => 'users#index'
  get 'admin' => 'admin#index'

  get '/stats' => 'stats#index'
  get '/stats/download' => 'stats#download'
  resources :demandes, only: [:new, :create]

  namespace :france_connect do
    get 'particulier' => 'particulier#login'
    get 'particulier/callback' => 'particulier#callback'
  end

  namespace :champs do
    get ':position/siret', to: 'siret#show', as: :siret
    get ':position/dossier_link', to: 'dossier_link#show', as: :dossier_link
    post ':position/carte', to: 'carte#show', as: :carte

    get ':champ_id/carte/features', to: 'carte#index', as: :carte_features
    post ':champ_id/carte/features', to: 'carte#create'
    post ':champ_id/carte/features/import', to: 'carte#import'
    patch ':champ_id/carte/features/:id', to: 'carte#update'
    delete ':champ_id/carte/features/:id', to: 'carte#destroy'

    post ':position/repetition', to: 'repetition#show', as: :repetition
    put 'piece_justificative/:champ_id', to: 'piece_justificative#update', as: :piece_justificative
  end

  resources :attachments, only: [:show, :destroy]

  get "patron" => "root#patron"
  get "accessibilite" => "root#accessibilite"
  get "suivi" => "root#suivi"
  post "dismiss_outdated_browser" => "root#dismiss_outdated_browser"

  get "contact", to: "support#index"
  post "contact", to: "support#create"

  get "contact-admin", to: "support#admin"

  post "webhooks/helpscout", to: "webhook#helpscout"
  match "webhooks/helpscout", to: lambda { |_| [204, {}, nil] }, via: :head

  #
  # Deprecated UI
  #

  namespace :users do
    resources :dossiers, only: [] do
      post '/carte/zones' => 'carte#zones'
      get '/carte' => 'carte#show'
      post '/carte' => 'carte#save'
      post '/repousser-expiration' => 'dossiers#extend_conservation'
    end

    # Redirection of legacy "/users/dossiers" route to "/dossiers"
    get 'dossiers', to: redirect('/dossiers')
    get 'dossiers/:id/recapitulatif', to: redirect('/dossiers/%{id}')
    get 'dossiers/invites/:id', to: redirect(path: '/invites/%{id}')

    get 'activate' => '/users/activate#new'
    patch 'activate' => '/users/activate#create'
  end

  # order matters: we don't want those routes to match /admin/procedures/:id
  get 'admin/procedures/new' => 'new_administrateur/procedures#new', as: :new_admin_procedure

  namespace :admin do
    get 'activate' => '/administrateurs/activate#new'
    patch 'activate' => '/administrateurs/activate#create'
    get 'procedures/archived' => 'procedures#archived'
    get 'procedures/draft' => 'procedures#draft'
    get 'procedures/:id/publication' => 'procedures#show', as: :procedure_publication

    resources :procedures, only: [:index, :destroy] do
      collection do
        get 'new_from_existing' => 'procedures#new_from_existing', as: :new_from_existing
      end

      member do
        delete :delete_logo
        delete :delete_deliberation
        delete :delete_notice
      end

      resources :mail_templates, only: [:index, :edit, :update]

      put 'archive' => 'procedures#archive', as: :archive
      get 'publish_validate' => 'procedures#publish_validate', as: :publish_validate
      put 'publish' => 'procedures#publish', as: :publish
      post 'transfer' => 'procedures#transfer', as: :transfer
      put 'clone' => 'procedures#clone', as: :clone

      resource :attestation_template, only: [:edit, :update, :create]

      post 'attestation_template/disactivate' => 'attestation_templates#disactivate'
      patch 'attestation_template/disactivate' => 'attestation_templates#disactivate'

      post 'attestation_template/preview' => 'attestation_templates#preview'
      patch 'attestation_template/preview' => 'attestation_templates#preview'

      delete 'attestation_template/logo' => 'attestation_templates#delete_logo'
      delete 'attestation_template/signature' => 'attestation_templates#delete_signature'
    end

    namespace :assigns do
      get 'show' # delete after fixed tests admin/instructeurs/show_spec without this line
    end

    resources :instructeurs, only: [:index, :create, :destroy]
  end

  resources :invites, only: [:show, :destroy] do
    collection do
      post 'dossier/:dossier_id', to: 'invites#create', as: :dossier
    end
  end

  #
  # API
  #

  authenticated :user, lambda { |user| user.administrateur_id && Flipper.enabled?(:administrateur_graphql, user) } do
    mount GraphqlPlayground::Rails::Engine, at: "/graphql", graphql_path: "/api/v2/graphql"
  end

  namespace :api do
    namespace :v1 do
      resources :procedures, only: [:index, :show] do
        resources :dossiers, only: [:index, :show]
      end
    end

    namespace :v2 do
      post :graphql, to: "graphql#execute"
    end
  end

  #
  # User
  #

  scope module: 'users' do
    namespace :commencer do
      get '/test/:path/dossier_vide', action: 'dossier_vide_pdf_test', as: :dossier_vide_test
      get '/test/:path', action: 'commencer_test', as: :test
      get '/:path', action: 'commencer'
      get '/:path/dossier_vide', action: 'dossier_vide_pdf', as: :dossier_vide
      get '/:path/sign_in', action: 'sign_in', as: :sign_in
      get '/:path/sign_up', action: 'sign_up', as: :sign_up
      get '/:path/france_connect', action: 'france_connect', as: :france_connect
    end

    resources :dossiers, only: [:index, :show, :new] do
      member do
        get 'identite'
        patch 'update_identite'
        get 'siret'
        post 'siret', to: 'dossiers#update_siret'
        get 'etablissement'
        get 'brouillon'
        patch 'brouillon', to: 'dossiers#update_brouillon'
        get 'modifier', to: 'dossiers#modifier'
        patch 'modifier', to: 'dossiers#update'
        get 'merci'
        get 'demande'
        get 'messagerie'
        post 'commentaire' => 'dossiers#create_commentaire'
        post 'ask_deletion'
        get 'attestation'
      end

      collection do
        get 'recherche'
      end
    end
    resource :feedback, only: [:create]
    get 'demarches' => 'demarches#index'

    get 'profil' => 'profil#show'
    post 'renew-api-token' => 'profil#renew_api_token'
    # allow refresh 'renew api token' page
    get 'renew-api-token' => redirect('/profil')
    patch 'update_email' => 'profil#update_email'
  end

  #
  # Instructeur
  #

  scope module: 'instructeurs', as: 'instructeur' do
    get 'avis', to: 'avis#index', as: 'all_avis'

    # this redirections are ephemeral, to ensure that emails sent to experts before are still valid
    # TODO : they will be removed in September, 2020
    get 'avis/:id', to: redirect('/procedures/old/avis/%{id}')
    get 'avis/:id/sign_up/email/:email', to: redirect("/procedures/old/avis/%{id}/sign_up/email/%{email}"), constraints: { email: /.*/ }

    resources :procedures, only: [:index, :show], param: :procedure_id do
      member do
        resources :groupes, only: [:index, :show], controller: 'groupe_instructeurs' do
          member do
            post 'add_instructeur'
            delete 'remove_instructeur'
          end
        end

        resources :avis, only: [:show, :update] do
          get '', action: 'procedure', on: :collection, as: :procedure

app/controllers/admin/procedures_controller.rb
class Admin::ProceduresController < AdminController
  include SmartListing::Helper::ControllerExtensions
  helper SmartListing::Helper

  before_action :retrieve_procedure, only: [:show, :delete_logo, :delete_deliberation, :delete_notice, :publish_validate, :publish]

  def index
    if current_administrateur.procedures.count != 0
      @procedures = smart_listing_create :procedures,
        current_administrateur.procedures.publiees.order(published_at: :desc),
        partial: "admin/procedures/list",
        array: true

      active_class
    else
      redirect_to new_from_existing_admin_procedures_path
    end
  end

  def archived
    @procedures = smart_listing_create :procedures,
      current_administrateur.procedures.closes.order(published_at: :desc),
      partial: "admin/procedures/list",
      array: true

    archived_class

    render 'index'
  end

  def draft
    @procedures = smart_listing_create :procedures,
      current_administrateur.procedures.brouillons.order(created_at: :desc),
      partial: "admin/procedures/list",
      array: true

    draft_class

    render 'index'
  end

  def show
    if @procedure.brouillon?
      @procedure_lien = commencer_test_url(path: @procedure.path)
    else
      @procedure_lien = commencer_url(path: @procedure.path)
    end
    @procedure.path = @procedure.suggested_path(current_administrateur)
    @current_administrateur = current_administrateur
  end

  def destroy
    procedure = current_administrateur.procedures.find(params[:id])

    if procedure.can_be_deleted_by_administrateur?
      procedure.discard_and_keep_track!(current_administrateur)

      flash.notice = 'Démarche supprimée'
      redirect_to admin_procedures_draft_path
    else
      render json: {}, status: 403
    end
  end

  def publish_validate
    @procedure.assign_attributes(publish_params)
  end

  def publish
    @procedure.assign_attributes(publish_params)

    @procedure.publish_or_reopen!(current_administrateur)

    flash.notice = "Démarche publiée"
    render js: "window.location='#{admin_procedures_path}'"
  rescue ActiveRecord::RecordInvalid
    respond_to do |format|
      format.js { render :publish_validate }
    end
  end

  def transfer
    admin = Administrateur.by_email(params[:email_admin].downcase)

    if admin.nil?
      respond_to do |format|
        format.js { render :transfer, status: :not_found }
      end
    else
      procedure = current_administrateur.procedures.find(params[:procedure_id])
      procedure.clone(admin, false)

      flash.now.notice = "La démarche a correctement été clonée vers le nouvel administrateur."

      respond_to(&:js)
    end
  end

  def archive
    procedure = current_administrateur.procedures.find(params[:procedure_id])
    procedure.close!

    flash.notice = "Démarche close"
    redirect_to admin_procedures_path

  rescue ActiveRecord::RecordNotFound
    flash.alert = 'Démarche inexistante'
    redirect_to admin_procedures_path
  end

  def clone
    procedure = Procedure.find(params[:procedure_id])
    new_procedure = procedure.clone(current_administrateur, cloned_from_library?)

    if new_procedure.valid?
      flash.notice = 'Démarche clonée'
      redirect_to edit_admin_procedure_path(id: new_procedure.id)
    else
      if cloned_from_library?
        flash.alert = new_procedure.errors.full_messages
        redirect_to new_from_existing_admin_procedures_path
      else
        flash.alert = new_procedure.errors.full_messages
        redirect_to admin_procedures_path
      end
    end

  rescue ActiveRecord::RecordNotFound
    flash.alert = 'Démarche inexistante'
    redirect_to admin_procedures_path
  end

  SIGNIFICANT_DOSSIERS_THRESHOLD = 30

  def new_from_existing
    significant_procedure_ids = Procedure
      .publiees_ou_closes
      .joins(:dossiers)
      .group("procedures.id")
      .having("count(dossiers.id) >= ?", SIGNIFICANT_DOSSIERS_THRESHOLD)
      .pluck('procedures.id')

    @grouped_procedures = Procedure
      .includes(:administrateurs, :service)
      .where(id: significant_procedure_ids)
      .group_by(&:organisation_name)
      .sort_by { |_, procedures| procedures.first.created_at }
    render layout: 'application'
  end

  def active_class
    @active_class = 'active'
  end

  def archived_class
    @archived_class = 'active'
  end

  def draft_class
    @draft_class = 'active'
  end

  def delete_logo
    @procedure.logo.purge_later

    flash.notice = 'le logo a bien été supprimé'
    redirect_to edit_admin_procedure_path(@procedure)
  end

  def delete_deliberation
    @procedure.deliberation.purge_later

    flash.notice = 'la délibération a bien été supprimée'
    redirect_to edit_admin_procedure_path(@procedure)
  end

  def delete_notice
    @procedure.notice.purge_later

    flash.notice = 'la notice a bien été supprimée'
    redirect_to edit_admin_procedure_path(@procedure)
  end

  private

  def cloned_from_library?
    params[:from_new_from_existing].present?
  end

  def publish_params
    params.permit(:path, :lien_site_web)
  end

  def procedure_params
    editable_params = [:libelle, :description, :organisation, :direction, :lien_site_web, :cadre_juridique, :deliberation, :notice, :web_hook_url, :euro_flag, :logo, :auto_archive_on]
    permited_params = if @procedure&.locked?
      params.require(:procedure).permit(*editable_params)
    else
      params.require(:procedure).permit(*editable_params, :duree_conservation_dossiers_dans_ds, :duree_conservation_dossiers_hors_ds, :for_individual, :path)
    end
    permited_params
  end
end

app/controllers/api/v1/procedures_controller.rb
class API::V1::ProceduresController < APIController
  before_action :fetch_procedure_and_check_token

  def show
    render json: { procedure: ProcedureSerializer.new(@procedure).as_json }
  end

  private

  def fetch_procedure_and_check_token
    @procedure = Procedure.for_api.find(params[:id])

    administrateur = find_administrateur_for_token(@procedure)
    if administrateur
      Current.administrateur = administrateur
    else
      render json: {}, status: :unauthorized
    end

  rescue ActiveRecord::RecordNotFound
    render json: {}, status: :not_found
  end
end

app/helpers/procedure_helper.rb
module ProcedureHelper
  def procedure_lien(procedure)
    if procedure.brouillon?
      commencer_test_url(path: procedure.path)
    else
      commencer_url(path: procedure.path)
    end
  end

  def procedure_libelle(procedure)
    parts = procedure.brouillon? ? [content_tag(:span, 'démarche en test', class: 'badge')] : []
    parts << procedure.libelle
    safe_join(parts, ' ')
  end

  def procedure_modal_text(procedure, key)
    action = procedure.close? ? :reopen : :publish
    t(action, scope: [:modal, :publish, key])
  end

  def types_de_champ_data(procedure)
    {
      isAnnotation: false,
      typeDeChampsTypes: TypeDeChamp.type_de_champ_types_for(procedure, current_user),
      typeDeChamps: procedure.types_de_champ.as_json_for_editor,
      baseUrl: admin_procedure_types_de_champ_path(procedure),
      directUploadUrl: rails_direct_uploads_url
    }
  end

  def types_de_champ_private_data(procedure)
    {
      isAnnotation: true,
      typeDeChampsTypes: TypeDeChamp.type_de_champ_types_for(procedure, current_user),
      typeDeChamps: procedure.types_de_champ_private.as_json_for_editor,
      baseUrl: admin_procedure_types_de_champ_path(procedure),
      directUploadUrl: rails_direct_uploads_url
    }
  end

  def procedure_auto_archive_date(procedure)
    I18n.l(procedure.auto_archive_on - 1.day, format: '%-d %B %Y')
  end

  def procedure_auto_archive_time(procedure)
    "à 23 h 59 (heure de " + Rails.application.config.time_zone + ")"
  end

  def procedure_auto_archive_datetime(procedure)
    procedure_auto_archive_date(procedure) + ' ' + procedure_auto_archive_time(procedure)
  end
end

app/views/new_administrateur/procedures/annotations.html.haml
= render partial: 'new_administrateur/breadcrumbs',
  locals: { steps: [link_to('Démarches', admin_procedures_path),
                    link_to(@procedure.libelle, admin_procedure_path(@procedure)),
                    'Configuration des annotations privées'], preview: true }

.container
  %h1 Configuration des annotations privées
  %br

  = react_component("TypesDeChampEditor", types_de_champ_private_data(@procedure))

app/views/new_administrateur/procedures/champs.html.haml
= render partial: 'new_administrateur/breadcrumbs',
  locals: { steps: [link_to('Démarches', admin_procedures_path),
                    link_to(@procedure.libelle, admin_procedure_path(@procedure)),
                    'Configuration des champs'], preview: true }

.container
  %h1 Configuration des champs
  %br

  = react_component("TypesDeChampEditor", types_de_champ_data(@procedure))

app/views/new_administrateur/procedures/edit.html.haml
= render partial: 'new_administrateur/breadcrumbs',
  locals: { steps: [link_to('Démarches', admin_procedures_path),
                    link_to(@procedure.libelle, admin_procedure_path(@procedure)),
                    'Description'] }
.procedure-form
  .procedure-form__columns.container
    = form_for @procedure,
      url: url_for({ controller: 'new_administrateur/procedures', action: :update, id: @procedure.id }),
      multipart: true,
      html: { class: 'form procedure-form__column--form' } do |f|

      %h1.page-title Description

      = render partial: 'new_administrateur/procedures/informations', locals: { f: f }

      .procedure-form__actions.sticky--bottom
        = link_to 'Annuler', admin_procedure_path(id: @procedure), class: 'button', data: { confirm: 'Êtes-vous sûr de vouloir annuler les modifications effectuées ?'}
        = f.button 'Enregistrer', class: 'button primary send'

    .procedure-form__column--preview
      .procedure-form__preview.sticky--top
        %h3.procedure-form__preview-title Aperçu
        .procedure-preview
          = render partial: 'shared/procedure_description', locals: { procedure: @procedure }

app/views/new_administrateur/procedures/jeton.html.haml
= render partial: 'new_administrateur/breadcrumbs',
  locals: { steps: [link_to('Démarches', admin_procedures_path),
                    link_to(@procedure.libelle, admin_procedure_path(@procedure)),
                    'Jeton'] }

.container
  %h1.page-title
    Configurer le jeton API Entreprise

.container
  %h1
  = form_with model: @procedure, url: url_for({ controller: 'new_administrateur/procedures', action: :update_jeton }), html: { class: 'form' } do |f|
    %p.explication
      Démarches Simplifiées utilise
      = link_to 'API Entreprise', "https://entreprise.api.gouv.fr/"
      qui permet de récupérer les informations administratives des entreprises et des associations.
      Si votre démarche nécessite des autorisations spécifiques que Démarches Simplifiées n'a pas par défaut, merci de renseigner ici le jeton
      = link_to 'API Entreprise', "https://entreprise.api.gouv.fr/demander_un_acces/"
      propre à votre démarche.

    = f.label :api_entreprise_token, "Jeton"
    = f.password_field :api_entreprise_token, class: 'form-control'
    .text-right
      = f.button 'Enregistrer', class: 'button primary send'

app/views/new_administrateur/procedures/monavis.html.haml
= render partial: 'new_administrateur/breadcrumbs',
  locals: { steps: [link_to('Démarches', admin_procedures_path),
                    link_to(@procedure.libelle, admin_procedure_path(@procedure)),
                    'MonAvis'] }

.container
  %h1.page-title
    Insérer un lien vers « MonAvis »

.container
  %h1
  = form_for @procedure, url: url_for({ controller: 'new_administrateur/procedures', action: :update_monavis }), multipart: true, html: { class: 'form' } do |f|
    = render partial: 'monavis', locals: { f: f }
    .text-right
      = f.button 'Enregistrer', class: 'button primary send'

app/views/new_administrateur/procedures/show.html.haml
= render partial: 'new_administrateur/breadcrumbs',
  locals: { steps: [link_to('Démarches', admin_procedures_path),
                    "#{@procedure.libelle} (crée le #{@procedure.created_at.strftime('%d/%m/%Y')})"] }

.container{ style: "display: flex; justify-content: flex-end; margin-bottom: 20px" }
  - if @procedure.brouillon?
    = link_to "Tester la démarche", sanitize_url(@procedure_lien), target: :blank, rel: :noopener, class: 'button primary', id: 'test-procedure-link'
  = button_to 'Publier la démarche', admin_procedure_publication_path(@procedure), method: :get, class: 'button primary', id: 'publish-procedure-link', disabled: @procedure.publiee? ? true : false

.container
  %h2.explication-libelle{ style: "font-weight: bold; font-size: 20px; margin-bottom: 20px;" } Indispensable avant publication
  .procedure-grid
    .card-admin
      %div
        %span.icon.accept
        %p.card-admin-status-accept Validé
      %div
        %p.card-admin-title Présentation
        %p.card-admin-subtitle Logo, nom, description
      .card-admin-action
        = button_to 'Modifier', edit_admin_procedure_path(@procedure), method: :get, class: 'card-admin-action-btn', id: "presentation"

    - if !@procedure.locked?
      .card-admin
        %div
          %span.icon.clock
          %p.card-admin-status-todo À faire
        %div
          %p.card-admin-title Formulaire
          %p.card-admin-subtitle Champs à remplir par les usagers
        .card-admin-action
          = button_to 'Modifier', champs_admin_procedure_path(@procedure), method: :get, class: 'card-admin-action-btn'

    .card-admin
      - if @procedure.service_id.present?
        %div
          %span.icon.accept
          %p.card-admin-status-accept Validé
      - else
        %div
          %span.icon.clock
          %p.card-admin-status-todo À faire
      %div
        %p.card-admin-title Service
        %p.card-admin-subtitle Choix du service de la démarche
      .card-admin-action
        = button_to 'Modifier', new_admin_service_path, params: { procedure_id: @procedure.id }, method: :get, class: 'card-admin-action-btn'

    .card-admin
      %div
        %span.icon.accept
        %p.card-admin-status-accept Validé
      %div
        %p.card-admin-title
          Administrateurs
          %span.badge.baseline
            = @procedure.administrateurs.count
        %p.card-admin-subtitle Gestion de la démarche
      .card-admin-action
        = button_to 'Modifier', admin_procedure_administrateurs_path(@procedure), method: :get, class: 'card-admin-action-btn', id: "administrateurs"

    .card-admin
      - if @procedure.instructeurs.count > 1
        %div
          %span.icon.accept
          %p.card-admin-status-accept Validé
      - else
        %div
          %span.icon.clock
          %p.card-admin-status-todo À faire
      %div
        %p.card-admin-title
          = feature_enabled?(:administrateur_routage) ? "Groupe Instructeurs" : "Instructeurs"
          - if feature_enabled?(:administrateur_routage)
            %span.badge.baseline
              = @procedure.groupe_instructeurs.count
          - else
            %span.badge.baseline
              = @procedure.instructeurs.count
        %p.card-admin-subtitle Suivi des dossiers
      .card-admin-action
        - if feature_enabled?(:administrateur_routage)
          = button_to 'Modifier', admin_procedure_groupe_instructeurs_path(@procedure), method: :get, class: 'card-admin-action-btn', id: "groupe-instructeurs"
        - else
          = button_to 'Modifier', admin_procedure_groupe_instructeur_path(@procedure, @procedure.defaut_groupe_instructeur), method: :get, class: 'card-admin-action-btn', id: "instructeurs"

    .card-admin
      %div
        %span.icon.preview
        %p.card-admin-status-todo À visualiser
      %div
        %p.card-admin-title
          Prévisualisation
        %p.card-admin-subtitle Apperçu de la démarche
      .card-admin-action
        = button_to 'Voir', apercu_admin_procedure_path(@procedure), method: :get, class: 'card-admin-action-btn'

  %h2.explication-libelle{ style: "font-weight: bold; font-size: 20px; margin-bottom: 20px;" } Pour aller plus loin
  .procedure-grid
    .card-admin
      - if @procedure.attestation_template.present?
        %div
          %span.icon.accept
          %p.card-admin-status-accept Activée
      - else
        %div
          %span.icon.clock
          %p.card-admin-status-todo À activer
      %div
        %p.card-admin-title Attestation
        %p.card-admin-subtitle Délivrance automatique pour les dossiers acceptés
      .card-admin-action
        = button_to 'Modifier', edit_admin_procedure_attestation_template_path(@procedure), method: :get, class: 'card-admin-action-btn'

    .card-admin
      %div
        %span.icon.clock
        %p.card-admin-status-todo À configurer
      %div
        %p.card-admin-title Configuration des emails
        %p.card-admin-subtitle Notifications automatiques
      .card-admin-action
        = button_to 'Modifier', admin_procedure_mail_templates_path(@procedure), method: :get, class: 'card-admin-action-btn'

    - if !@procedure.locked?
      .card-admin
        - if @procedure.types_de_champ_private.present?
          %div
            %span.icon.accept
            %p.card-admin-status-accept Validé
        - else
          %div
            %span.icon.clock
            %p.card-admin-status-todo À configurer
        %div
          %p.card-admin-title Annotations privées
          %p.card-admin-subtitle Champs à remplir par l’administration
        .card-admin-action
          = button_to 'Modifier', annotations_admin_procedure_path(@procedure), method: :get, class: 'card-admin-action-btn'

    .card-admin
      - if @procedure.api_entreprise_token.present?
        %div
          %span.icon.accept
          %p.card-admin-status-accept Validé
      - else
        %div
          %span.icon.clock
          %p.card-admin-status-todo À configurer
      %div
        %p.card-admin-title Jeton
        %p.card-admin-subtitle Configurer le jeton API entreprise
      .card-admin-action
        = button_to 'Modifier', jeton_admin_procedure_path(@procedure), method: :get, class: 'card-admin-action-btn'

    .card-admin
      - if @procedure.monavis_embed.present?
        %div
          %span.icon.accept
          %p.card-admin-status-accept Validé
      - else
        %div
          %span.icon.clock
          %p.card-admin-status-todo À configurer
      %div
        %p.card-admin-title MonAvis
        %p.card-admin-subtitle Avis des usagers sur votre démarche
      .card-admin-action
        = button_to 'Modifier', monavis_admin_procedure_path(@procedure), method: :get, class: 'card-admin-action-btn'